# Product Schema Example
# This file defines the structure for a Product model

fields:
  name:
    type: string
    length: 255
    nullable: false
    unique: false
    index: true
    comment: "Product name"
    validation:
      - "min:2"
      - "max:255"
    factory:
      - "fake()->productName()"

  slug:
    type: string
    length: 255
    nullable: false
    unique: true
    index: true
    comment: "URL-friendly product identifier"
    validation:
      - "regex:/^[a-z0-9-]+$/"
    factory:
      - "fake()->slug()"

  description:
    type: text
    nullable: true
    comment: "Product description"
    validation:
      - "max:2000"
    factory:
      - "fake()->paragraph(3)"

  price:
    type: decimal
    length: 8,2
    nullable: false
    default: 0.00
    comment: "Product price"
    validation:
      - "numeric"
      - "min:0"
      - "max:999999.99"
    factory:
      - "fake()->randomFloat(2, 10, 1000)"

  stock_quantity:
    type: integer
    nullable: false
    default: 0
    comment: "Available stock quantity"
    validation:
      - "integer"
      - "min:0"
    factory:
      - "fake()->numberBetween(0, 100)"

  is_active:
    type: boolean
    nullable: false
    default: true
    comment: "Product availability status"
    validation:
      - "boolean"
    factory:
      - "fake()->boolean(80)" # 80% chance of being true

  published_at:
    type: datetime
    nullable: true
    comment: "Product publication date"
    validation:
      - "date"
    factory:
      - "fake()->dateTimeBetween('-1 year', 'now')"

  sku:
    type: string
    length: 100
    nullable: false
    unique: true
    comment: "Stock Keeping Unit"
    validation:
      - "alpha_num"
      - "size:8"
    factory:
      - "strtoupper(fake()->lexify('????????'))"

relationships:
  category:
    type: belongsTo
    model: App\Models\Category
    foreign_key: category_id
    local_key: id
    
  tags:
    type: belongsToMany
    model: App\Models\Tag
    pivot_table: product_tags
    pivot_fields:
      - created_at
      - updated_at
    with_timestamps: true

  reviews:
    type: hasMany
    model: App\Models\Review
    foreign_key: product_id
    local_key: id

  images:
    type: hasMany
    model: App\Models\ProductImage
    foreign_key: product_id

  variants:
    type: hasMany
    model: App\Models\ProductVariant
    foreign_key: product_id

  supplier:
    type: belongsTo
    model: App\Models\Supplier
    foreign_key: supplier_id

options:
  table: products
  timestamps: true
  soft_deletes: true
  traits:
    - "App\Traits\Sluggable"
    - "App\Traits\Searchable"

metadata:
  version: "1.0"
  author: "TurboMaker"
  description: "Product schema for e-commerce application"
  created_at: "2024-08-02"
  tags:
    - "ecommerce"
    - "product"
    - "catalog"
