name: 💡 Feature Request
description: Suggest a new idea or feature for Laravel Arc
title: "[Feature] <Your short title here>"
labels: [type:feature]
body:

  - type: dropdown
    id: area
    attributes:
      label: Area / Component
      description: Which part of the codebase is affected?
      options:
        - generator
        - validation
        - docs
        - tests
        - cli
        - internal
    validations:
      required: true

  - type: textarea
    id: need
    attributes:
      label: What problem does this feature solve?
      placeholder: |
        Describe the pain point or need you're trying to address.
        Example: "Currently there's no support for date/time fields..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe your proposed solution
      placeholder: |
        How would you implement this feature? Include examples or expected YAML syntax if possible.
    validations:
      required: true
